1 mega commit
vitermakov/otusgo-final pull request #1
Opened 2023-02-07 21:06 UTC by vitermakov

##1 итерация

* white-, black-list хранятся во внешней БД
* пока нет cli
* сделаны unit-тесты
* алгоритм rate-limit fixed-win, хранилище in-memory. В следующей реализации поработаю с redis и постараюсь реализовать плавающее окно или leacky-bucket.
* сервис - на основе GRPC

2023-02-08 14:55 UTC, gna69 requested changes

2023-02-08 14:55 UTC, gna69 commented on internal/app/app.go
> +		stdlog.Fatalf("не удалось инициализировать приложение: %s", err)
Fatalf под капотом вызывает ф-ию os.Exit, которая завершает приложение сразу. Т.е. все defer' ы не отработают, а запущенные горутины будут моментально принудительно завершены.
Лучше в таком случае выбрасывать ошибку на уровень выше, где можно ее корректно обработать:

1. Вывести подробную информацию об ошибке в лог/систему сбора метрик/дебаг файлик;
2.Вывести user-friendly сообщение пользователю об ошибке.
3. Завершить приложение, корректно завершив рутины(Например отменив контекст) и освободив все выделенные ресурсы.

2023-02-08 14:55 UTC, gna69 commented on internal/app/deps/brutefp/deps.go
> +	case "memory":
"memory", "pgsql" и подобные константные значения в программе лучше выносить в константы, потому что:
1. Их можно переиспользовать в других местах программы и быть уверенным в том, что не будет опечатки в значении.
2. Константы позволяют документировать код (в случае строк это не очевидно, но в случае других типов данных работает отлично)

2023-02-08 14:55 UTC, gna69 commented on internal/app/deps/brutefp/deps.go
> +	return repos, err
В go сообществе принято возвращать валидные значения и nil, если все прошло хорошо и дефолтные значения типов и ошибку, если что-то пошло не так.
Такой подход защитит код от "невнимательного" программиста, который может случайно/специально игнорировать ошибку и при получении дефолтного значения он быстрее получит ошибку/не ожидаемое поведение/панику в случае с указателями.

2023-02-08 14:55 UTC, gna69 commented on internal/handler/grpc/dto/permit.go
> +		return model.PermitQuery{}, errors.New("ip address is not well-formed")
Вижу, что эта же ошибка возвращается на 35 строке
В таком случае можно вынести ее в переменную на уровне пакета и возвращать эту переменную
В случае, если во внешних пакетах она тоже нужна - можно сделать ее экспортируемой

2023-02-08 14:55 UTC, gna69 commented on internal/handler/grpc/ip_rule_impl.go
> +	if ruleType == model.RuleTypeAllow {
Можно избавиться от else:
```
tg  := "black-list"
if cond {
   tg = "white-list"
}
```
название листов можно так же унести в константы

2023-02-08 14:55 UTC, gna69 commented on internal/handler/grpc/ip_rule_impl.go
> +	return status.Error(s.Code(), s.Message())
Чтобы избежать лишнего выделения памяти в s можно заинлайнить: `status.Error(rqres.FromError(err).Code(), s.Message())`

2023-02-08 14:55 UTC, gna69 commented on internal/model/ip_rule_errors.go
> +	ErrRuleTypeUnk  = errors.New("неизвестный тип правила (allow/deny)")
Лучше ошибки и сообщения в консоль писать латиницей, так как кириллица может не на всех системах корректно отображаться

2023-02-08 14:55 UTC, gna69 commented on internal/repository/memory/ip_rule.go
> +		// если кто-то спросит что это за жесть - линтер считает это более правильным чем вложенные if
Возможно линтер ждет что-то вроде такого:
```
if search.IPNetExact && strings.Compare(rule.IPNet.String(), search.IPNet.String()) != 0 {

} else if !search.IPNetExact && !rule.IPNet.Contains(search.IPNet.IP) {

}
```

2023-02-08 14:55 UTC, gna69 commented on internal/service/permit_checker.go
> +	checks := []struct {
Для того, чтобы не выделять память под проверки при каждом запуске метода Check можно унести их на уровень пакета.

2023-02-08 14:55 UTC, gna69 commented on pkg/logger/logger_test.go
> +	defer file.Close()
Можно объединить в один defer с замыканием

2023-02-08 15:02 UTC, gna69 commented on Makefile
> +	$(BIN_APP) -config ./configs/brutefp_config.json
Развертывание микросервиса должно осуществляться командой make run (внутри docker compose up) в директории с проектом - из требований к проекту.

2023-02-19 11:30 UTC, vitermakov commented on internal/app/app.go
> +		stdlog.Fatalf("не удалось инициализировать приложение: %s", err)
Да уж, делал эту функцию как времянку и так к ней и не вернулся.
Там идея была в том, что все вызовы 3 частей приложения (инициализация, пуск, завершение) должны быть внутри Execute, поэтому сделал еще один контекст внутри, чтобы использовать отмену cancel() внутри функции.

Сообщение пользователю об ошибке в наличии

2023-02-19 12:31 UTC, vitermakov commented on internal/app/deps/brutefp/deps.go
> +	case "memory":
Согласен, ввел константы, в одном месте за пределами пакета их использовал

2023-02-19 12:45 UTC, vitermakov commented on internal/app/deps/brutefp/deps.go
> +	return repos, err
Тут я пытался понять в чем конкретно была моя ошибка, так как я 
- при отсутствии ошибки возвращаю &Repos{ .... } с установленными значениями и nil в виде ошибки (err == nil)
- при наличии ошибки возвращаю <nil> (это значение по-умолчанию для *Repos) и не-nil ошибку.

В таком случае "невнимательный программист" быстрее нарвется на панику, если из-вне он игнорирует ошибку и пытается использовать первый аргумент без проверки.

Но на всякий случай на строчке 31 изменил repos *Repos на repos = &Repos{}, но пока не понимаю чем это лучше.

2023-02-19 12:53 UTC, vitermakov commented on internal/handler/grpc/dto/permit.go
> +		return model.PermitQuery{}, errors.New("ip address is not well-formed")
Да, вынес ошибки в отдельный файл, сделал экспортируемым, так как обычно это это используется в тестах

2023-02-19 13:05 UTC, vitermakov commented on internal/handler/grpc/ip_rule_impl.go
> +	if ruleType == model.RuleTypeAllow {
переделал

2023-02-19 13:06 UTC, vitermakov commented on internal/handler/grpc/ip_rule_impl.go
> +	return status.Error(s.Code(), s.Message())
тут s используется два раза
status.Error(s.Code(), s.Message())

2023-02-19 13:30 UTC, vitermakov commented on internal/model/ip_rule_errors.go
> +	ErrRuleTypeUnk  = errors.New("неизвестный тип правила (allow/deny)")
ну эти строки в бинаре сохранятся же в юникоде, а он (вроде) спасает нас от боли. Или есть вариант использовать эту программку на стиральной машинке :-) ?

Переделал на латиницу

2023-02-19 14:18 UTC, vitermakov commented on internal/service/permit_checker.go
> +	checks := []struct {
вынес на уровень члена структуры, который инициализируется один раз, на уровень пакета это трудно вынести, там же все зависит от конкретных лимитов, а имя бакета вообще зависит от данных запроса.

Провел небольшой рефакторинг, чтобы формирование имени бакета спрятать в отдельную структуру, так как эта логика используется в нескольких местах и я до этого ее по сути дублировал.

2023-02-19 14:20 UTC, vitermakov commented on Makefile
> +	$(BIN_APP) -config ./configs/brutefp_config.json
На этом эта развертывания пока еще нет

2023-02-19 15:48 UTC, vitermakov commented on pkg/logger/logger_test.go
> +	defer file.Close()
объеденил в след. итерации, тут пропустил почему-то

2023-02-19 16:06 UTC, gna69 commented on internal/app/deps/brutefp/deps.go
> +	return repos, err
Ошибки тут нет с точки зрения программы, код будет отрабатывать как нужно, просто в go принято возвращать значения так, чтобы при чтении кода было понятно поведение функции при возникновении ошибки и при ее отсутствии. В коде это отражается, например, так:
```
type someStruct struct {
  name string
}

func someF() (int, string, someStruct, err) {
  // some work ...
  if err := anotherSomeF(); err != nil {
    return 0, "", someStruct{}, err
  }
  return intVal, "success", someStruct{name: "testName"}, nil
}
```

2023-02-20 12:44 UTC, vitermakov commented on internal/repository/memory/ip_rule.go
> +		// если кто-то спросит что это за жесть - линтер считает это более правильным чем вложенные if
поправил и сработало!
но со стороны выглядит более запутано чем короткие if

2023-03-03 20:59 UTC, merged